# Generated by Django 5.2.4 on 2025-07-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Clothing'), ('ML', 'Accessories')], max_length=2),
        ),
    ]
